# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=20, verbose_name='\u5bc6\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('dept', models.CharField(default='cp', max_length=4, verbose_name='\u90e8\u95e8')),
            ],
            options={
                'db_table': 'UserInfo',
                'verbose_name': '\u7528\u6237\u6ce8\u518c\u4fe1\u606f',
            },
        ),
    ]
