# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance_Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=30)),
                ('mem', models.IntegerField(default=1024)),
                ('cpu', models.IntegerField(default=1)),
                ('disk', models.IntegerField(default=50)),
                ('bandwidth', models.CharField(max_length=10)),
                ('os', models.CharField(max_length=30)),
                ('storage', models.CharField(default='sas', max_length=30)),
                ('expired', models.IntegerField(default=30)),
            ],
            options={
                'db_table': 'instance_orders',
            },
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
