# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20170518_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(max_length=20)),
                ('opt_mode', models.CharField(max_length=20)),
                ('opt_user', models.CharField(max_length=30)),
                ('opt_ip', models.GenericIPAddressField(protocol='IPV4')),
                ('opt_time', models.DateTimeField()),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
