# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='create_Logs',
        ),
        migrations.AlterModelTable(
            name='create_logs',
            table='create_logs',
        ),
    ]
