# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instance_Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=30)),
                ('mem', models.IntegerField(default=1024)),
                ('cpu', models.IntegerField(default=1)),
                ('disk', models.IntegerField(default=50)),
                ('bandwidth', models.CharField(max_length=10)),
                ('os', models.CharField(max_length=30)),
                ('storage', models.CharField(default='sas', max_length=30)),
                ('expired', models.IntegerField(default=30)),
            ],
            options={
                'db_table': 'instance_orders',
                'verbose_name': '\u521b\u5efa\u5b9e\u4f8b',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=20, verbose_name='\u5bc6\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('dept', models.CharField(default='cp', max_length=4, verbose_name='\u90e8\u95e8')),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'userinfo',
                'verbose_name': '\u7528\u6237\u6ce8\u518c\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('logintime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'log',
                'verbose_name': '\u767b\u9646\u65e5\u5fd7',
            },
        ),
    ]
