# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default=None, max_length=255)),
                ('dept_approval_time', models.DateTimeField()),
                ('dept_reason', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'dept_reason',
            },
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
    ]
