# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('dis_playname', models.CharField(max_length=50)),
                ('net_name', models.CharField(max_length=20)),
                ('net_desc', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'network',
            },
        ),
    ]
