# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_name', models.CharField(max_length=15)),
                ('rx_new', models.CharField(max_length=20)),
                ('rx_old', models.CharField(max_length=20)),
                ('tx_new', models.CharField(max_length=20)),
                ('tx_old', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
            ],
            options={
                'db_table': 'instance_log',
            },
        ),
    ]
