# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=36)),
                ('dept_admin', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'power',
            },
        ),
    ]
