# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0002_remove_network_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='visibility',
        ),
    ]
