# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0002_auto_20170613_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d')),
                ('logintime', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'log',
                'verbose_name': '\u767b\u9646\u65e5\u5fd7',
            },
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
