# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0002_instancelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancelog',
            name='rx_new',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='instancelog',
            name='rx_old',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='instancelog',
            name='tx_new',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='instancelog',
            name='tx_old',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
