# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0002_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dept',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
