# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0002_os_os_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
