# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0002_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='network',
            field=models.IntegerField(default=1),
        ),
    ]
