# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0002_auto_20170922_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='VcloudReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default=None, max_length=255)),
                ('vcloud_approval_time', models.DateTimeField()),
                ('vcloud_reason', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'vcloud_reason',
            },
        ),
    ]
