# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0002_auto_20170907_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='name',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
