# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0003_vcloudreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptreason',
            name='approval_person',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='vcloudreason',
            name='approval_person',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
