# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0003_orderdetail_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name=uuid.uuid4)),
                ('host_name', models.CharField(max_length=20)),
                ('port_name', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('traffic_in', models.IntegerField(default=0)),
                ('traffic_out', models.IntegerField(default=0)),
                ('server_name', models.CharField(max_length=20)),
                ('mac_address', models.CharField(default='0000-0000-0000', max_length=15)),
            ],
            options={
                'db_table': 'traffic',
            },
        ),
        migrations.RenameField(
            model_name='ip',
            old_name='traffice_in',
            new_name='traffic_in',
        ),
        migrations.RenameField(
            model_name='ip',
            old_name='traffice_out',
            new_name='traffic_out',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='name',
        ),
    ]
