# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0003_auto_20170614_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='logintime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
