# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0003_auto_20171027_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instancelog',
            old_name='ip_address',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='instancelog',
            old_name='ins_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='instancelog',
            name='state',
            field=models.BooleanField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='instancelog',
            name='tap',
            field=models.CharField(default='0000-0000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='instancelog',
            name='rx_new',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instancelog',
            name='rx_old',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instancelog',
            name='tx_new',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instancelog',
            name='tx_old',
            field=models.IntegerField(),
        ),
    ]
