# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0003_remove_order_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visibility',
            field=models.BooleanField(default=0),
        ),
    ]
