# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0004_order_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='visibility',
        ),
    ]
