# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0004_orderdetail_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='dept',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
