# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0004_auto_20170912_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic',
            name='id',
        ),
        migrations.AlterField(
            model_name='traffic',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4),
        ),
    ]
