# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0005_userinfo_reg_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='instance_Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=30)),
                ('mem', models.IntegerField(default=1024)),
                ('cpu', models.IntegerField(default=1)),
                ('disk', models.IntegerField(default=50)),
                ('bandwidth', models.CharField(max_length=10)),
                ('os', models.CharField(max_length=30)),
                ('storage', models.CharField(default='sas', max_length=30)),
                ('expired', models.IntegerField(default=30)),
            ],
            options={
                'db_table': 'instance_orders',
                'verbose_name': '\u521b\u5efa\u5b9e\u4f8b',
            },
        ),
    ]
