# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0005_auto_20170912_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
