# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0005_auto_20170808_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='os',
            field=models.CharField(max_length=20),
        ),
    ]
