# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloudapp', '0007_auto_20170808_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='dept',
        ),
        migrations.AddField(
            model_name='order',
            name='dept',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
